Repository Refresh-Onecake/Onecake_FrontEnd, pull requests merged in 2022-07, with the labels that each got.

#22 달력 컴포넌트 및 bottomSheet 컴포넌트
  babel.config.js
  db.json
  index.js
  ios/Podfile.lock
  package.json
  src/asset/arrow-back.png
  src/components/common/BottomSheet.tsx
  src/components/common/ScrollCalendar.tsx
  src/components/index.ts
  src/components/seller/MenuList.tsx
  src/components/seller/OrderManageContent.tsx
  src/enum/queryKeys.ts
  src/recoil/atom.ts
  src/screens/Order.tsx
  src/screens/navigator/StackNavigator.tsx
  src/screens/navigator/navigationStackTypes.ts
  src/screens/sellerOrder/OrderManageList.tsx
  src/screens/sellerOrder/OrderSheet.tsx
  src/screens/sellerOrder/SellerOrder.tsx
  src/services/orderService.ts
  src/utils/assert.ts
  src/utils/index.ts
Labels: enhancement

#23 판매자 주문관리 페이지 구현
  db.json
  src/asset/close_X.png
  src/components/common/BottomSheet.tsx
  src/components/common/ModalHeader.tsx
  src/components/common/RadioList.tsx
  src/components/common/ScrollCalendar.tsx
  src/components/index.ts
  src/components/seller/OrderManageContent.tsx
  src/components/seller/OrderManageFooter.tsx
  src/enum/appKeys.ts
  src/enum/index.ts
  src/enum/orderStatusKeys.ts
  src/enum/queryKeys.ts
  src/recoil/atom.ts
  src/screens/enterMenu/EnterMenu.tsx
  src/screens/navigator/StackNavigator.tsx
  src/screens/sellerOrder/OrderManageList.tsx
  src/screens/sellerOrder/OrderSheet.tsx
  src/screens/sellerOrder/SellerOrder.tsx
  src/services/orderService.ts
  src/utils/dateFormatParser.tsx
  src/utils/index.ts
  src/utils/priceFormatParser.ts
  src/utils/timeFormatOnKorea.ts
Labels: enhancement

#24 중간발표 릴리즈를 위한 기존 구현 기능 버그 fix
  .eslintrc.js
  App.tsx
  ios/Onecake_FrontEnd.xcodeproj/project.pbxproj
  ios/Onecake_FrontEnd/Info.plist
  ios/Onecake_FrontEnd/Onecake_FrontEnd.entitlements
  ios/assets/src/asset/arrow-back.png
  ios/assets/src/asset/back-btn.png
  ios/assets/src/asset/check_Icon_default_active.png
  ios/assets/src/asset/check_circle_active.png
  ios/assets/src/asset/check_circle_none.png
  ios/assets/src/asset/chevron_right.png
  ios/assets/src/asset/close_X.png
  ios/assets/src/asset/login_logo.png
  ios/assets/src/asset/login_title.png
  ios/assets/src/asset/plus_btn_gray.png
  ios/assets/src/asset/visible_active.png
  ios/assets/src/asset/visible_none.png
  src/asset/back-btn.png
  src/asset/check_Icon_default_active.png
  src/asset/check_circle_active.png
  src/asset/check_circle_none.png
  src/asset/chevron_right.png
  src/asset/visible_active.png
  src/asset/visible_none.png
  src/components/seller/MenuList.tsx
  src/screens/auth/SelectUserType.tsx
  src/screens/auth/SignIn.tsx
  src/screens/auth/SignUp.tsx
  src/screens/enterMenu/EnterMenu.tsx
  src/screens/enterStore/EnterComplete.tsx
  src/screens/enterStore/EnterStart.tsx
  src/screens/enterStore/EnterStore.tsx
  src/screens/navigator/StackNavigator.tsx
  src/screens/sellerOrder/SellerOrder.tsx
  src/styles/AppStyles.ts
  src/utils/index.ts
  src/utils/parseTime.ts
Labels: bug

#29 판매자 마이페이지 구현
  src/components/common/InfoModal.tsx
  src/components/seller/MenuRenderList.tsx
  src/components/seller/MenuRenderListDropdown.tsx
  src/components/seller/MenuRenderListItem.tsx
  src/components/seller/SettingSeller/SettingSeller.tsx
  src/components/seller/SettingSeller/index.ts
  src/enum/queryKeys.ts
  src/hooks/useGetSellerChatUrlQuery.ts
  src/screens/Contact.tsx
  src/screens/MyPage.tsx
  src/screens/navigator/MainNavigator.tsx
  src/services/contactService.ts
  src/services/index.ts
  src/services/menuService.ts
  src/services/orderService.ts
Labels: enhancement

#30 탈퇴기능 구현 및 도메인 주소 변경
  src/components/seller/MenuRenderListDropdown.tsx
  src/components/seller/SettingSeller/ReSign.tsx
  src/components/seller/SettingSeller/SettingSeller.tsx
  src/components/seller/SettingSeller/index.ts
  src/components/seller/ToggleList.tsx
  src/enum/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useGetSellerMenuSheetByMenuId.ts
  src/hooks/useLogoutAndReSignQuery.ts
  src/recoil/atom.ts
  src/screens/Contact.tsx
  src/screens/Terms/index.ts
  src/screens/enterMenu/EnterMenu.tsx
  src/screens/enterMenu/EnterMenuSheet.tsx
  src/screens/enterMenu/types.tsx
  src/screens/enterStore/EnterStore.tsx
  src/screens/enterStore/types.ts
  src/screens/navigator/MainNavigator.tsx
  src/screens/navigator/StackNavigator.tsx
  src/screens/navigator/navigationStackTypes.ts
  src/services/authService.ts
  src/services/contactService.ts
  src/services/enterService.ts
  src/services/menuService.ts
  src/services/orderService.ts
  src/styles/commonStyles.ts
Labels: enhancement

#36 Feature/android splash
  android/app/build.gradle
  android/app/src/main/res/drawable-hdpi/launch_screen.png
  android/app/src/main/res/drawable-mdpi/launch_screen.png
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxxhdpi/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/gradle.properties
  package.json
  src/screens/auth/SignIn.tsx
  src/screens/store/StoreTitleInfo.tsx
Labels: bug, enhancement

#37 feat : 탈퇴 시 사용자 이름이 보이는 기능 추가 및 기타 UI 수정
  App.tsx
  ios/Onecake_FrontEnd.xcodeproj/project.pbxproj
  ios/Onecake_FrontEnd/AppDelegate.h
  ios/Onecake_FrontEnd/AppDelegate.mm
  ios/Onecake_FrontEnd/Info.plist
  ios/Podfile
  ios/Podfile.lock
  ios/assets/src/asset/congratulation.png
  src/asset/congratulation.png
  src/components/consumer/StoreInfo.tsx
  src/components/seller/SettingSeller/ReSign.tsx
  src/enum/queryKeys.ts
  src/hooks/index.ts
  src/hooks/useGetMemberInfoQuery.ts
  src/screens/Stores.tsx
  src/screens/auth/SelectUserType.tsx
  src/screens/auth/SignIn.tsx
  src/screens/enterMenu/EnterMenu.tsx
  src/screens/enterStore/EnterComplete.tsx
  src/screens/enterStore/EnterStore.tsx
  src/screens/navigator/MainNavigator.tsx
  src/screens/store/StoreDetail.tsx
  src/screens/store/StoreTitleInfo.tsx
  src/services/authService.ts
  src/services/menuService.ts
Labels: bug, enhancement

#38 codePush를 위한 세팅구현
  App.tsx
  android/app/build.gradle
  android/app/src/main/java/com/onecake_frontend/MainApplication.java
  android/gradle.properties
  android/settings.gradle
  ios/Onecake_FrontEnd.xcodeproj/project.pbxproj
  ios/Onecake_FrontEnd/AppDelegate.mm
  ios/Onecake_FrontEnd/Info.plist
  ios/Podfile.lock
  package.json
  src/screens/auth/SignIn.tsx
Labels: enhancement
